name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Set timezone
              run: |
                sudo ln -sf /usr/share/zoneinfo/Asia/Singapore /etc/localtime
                echo "Asia/Singapore" | sudo tee /etc/timezone
                date
    
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Clean Install Dependencies
              run: npm ci

            - name: Run Jest Tests
              run: npm run test
